project_id = "bkdyblcbqpnoigmodlpj"

[auth]
site_url = "https://ultra-fischer-retry.vercel.app"
additional_redirect_urls = [
  "https://ultra-fischer-retry.vercel.app/home.html?auth=recovery",
  "http://localhost:4175/home.html?auth=recovery"
]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false
enable_refresh_token_rotation = true

[auth.email]
enable_signup = true
enable_confirmations = true
max_frequency = "1m"
otp_length = 6
otp_expiry = 600
secure_password_change = true

[auth.rate_limit]
token_verifications = 5
email_sent = 2

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
